#! /bin/bash
clear

cd /u/prevenda/work

DATA_SUP=`date '+%Y%m%d%H%M'`

stty intr ""
DLC=/usr/dlc
PROCFG=/admcom/progress-cliente.cfg
export DLC PROCFG


export PROPATH="../app"

mpro -pf /admcom/pf/bancos.pf  -p /u/prevenda/app/inicio.p -param $1

echo " "
echo " "
echo " "
echo " TERMINAL DESCONECTADO - PRESSIONE QUALQUER TECLA PARA RETORNAR "
echo " "
echo "                 OU DESLIGUE O COMPUTADOR AGORA"
read VAR

stty intr ^C
